#!/usr/bin/env python3
import argparse, json, shutil
from pathlib import Path

PROJECT_GODOT = '''; Engine configuration file.
; Generated by godot-project-scaffolder.

config_version=5

[application]
config/name="{project_name}"
run/main_scene="res://scenes/Main.tscn"
config/features=PackedStringArray("4.0")

[display]
window/size/viewport_width=1280
window/size/viewport_height=720
window/stretch/mode="canvas_items"
window/stretch/aspect="expand"

[input]
tap_select={{
"deadzone": 0.5,
"events": []
}}
'''

MAIN_TSCN = '''[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://scripts/main.gd" id="1_main"]

[node name="Main" type="Node2D"]
script = ExtResource("1_main")

[node name="World" type="Node2D" parent="."]

[node name="UI" type="CanvasLayer" parent="."]
'''

MAIN_GD = '''extends Node2D

@onready var world: Node2D = $World
@onready var ui: CanvasLayer = $UI

func _ready() -> void:
    print("Main scene ready")
'''

GAME_STATE_GD = '''extends Node
class_name GameState

signal state_changed(key: String, value: Variant)

var values: Dictionary = {}

func set_value(key: String, value: Variant) -> void:
    values[key] = value
    state_changed.emit(key, value)

func get_value(key: String, default_value: Variant = null) -> Variant:
    return values.get(key, default_value)
'''

INPUT_ROUTER_GD = '''extends Node
class_name InputRouter

signal primary_pressed(screen_position: Vector2)
signal primary_released(screen_position: Vector2)

func _unhandled_input(event: InputEvent) -> void:
    if event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_LEFT:
        if event.pressed:
            primary_pressed.emit(event.position)
        else:
            primary_released.emit(event.position)
    elif event is InputEventScreenTouch:
        if event.pressed:
            primary_pressed.emit(event.position)
        else:
            primary_released.emit(event.position)
'''

def slug(s):
    return ''.join(ch.lower() if ch.isalnum() else '_' for ch in s).strip('_') or 'godot_project'

def main():
    p = argparse.ArgumentParser(description='Create a Godot project skeleton.')
    p.add_argument('--project-name', required=True)
    p.add_argument('--output-dir', required=True)
    p.add_argument('--preset', default='mobile_2d')
    p.add_argument('--force', action='store_true')
    args = p.parse_args()

    out = Path(args.output_dir)
    if out.exists() and args.force:
        shutil.rmtree(out)
    out.mkdir(parents=True, exist_ok=True)
    for rel in [
        'scenes/rooms','scenes/ui','scripts','assets/sprites','assets/ui','assets/audio','assets/fonts',
        'generated_assets','art_source','design','pipeline_runs','exports','tools'
    ]:
        (out / rel).mkdir(parents=True, exist_ok=True)
    (out / 'project.godot').write_text(PROJECT_GODOT.format(project_name=args.project_name))
    (out / 'scenes/Main.tscn').write_text(MAIN_TSCN)
    (out / 'scripts/main.gd').write_text(MAIN_GD)
    (out / 'scripts/game_state.gd').write_text(GAME_STATE_GD)
    (out / 'scripts/input_router.gd').write_text(INPUT_ROUTER_GD)
    manifest = {
        'project_name': args.project_name,
        'slug': slug(args.project_name),
        'preset': args.preset,
        'platform_focus': ['mobile','desktop'],
        'main_scene': 'scenes/Main.tscn'
    }
    (out / 'design/project_manifest.json').write_text(json.dumps(manifest, indent=2))
    (out / 'README.md').write_text(f'''# {args.project_name}\n\nGenerated Godot project skeleton.\n\n## Folders\n\n- `assets/`: Godot-imported assets\n- `generated_assets/`: outputs from sprite-generation skills\n- `art_source/`: reference/source art\n- `pipeline_runs/`: generated pipeline work folders\n- `design/`: design docs and manifests\n''')
    print(out)

if __name__ == '__main__':
    main()
